export const UPDATE_CURRENT_INPUT = 'UPDATE_CURRENT_INPUT';
export const CLEAR_CURRENT_INPUT = 'CLEAR_CURRENT_INPUT';
export const VALIDATE_CURRENT_INPUT = 'VALIDATE_CURRENT_INPUT';
export const UPDATE_LOCKSTATUS = 'UPDATE_LOCKSTATUS';
export const UPDATE_CURRENT_PIN = 'UPDATE_CURRENT_PIN';
export const INIT_STORE = 'INIT_STUFF';